spring:
  datasource:
    url: jdbc:mysql://ye1998.host:3306/auth2
    username: root
    password: 135246
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8082
security:
  oauth2:
    client:
      client-id: SampleClientId
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
        key-value: cjs
